"""Online paper search agent stub."""

from __future__ import annotations

from uuid import uuid5, NAMESPACE_URL

from app.models import PaperRecord, TodoTask


class PaperSearchAgent:
    """Return mock online paper records for a TODO item."""

    def search(self, task: TodoTask, *, top_k: int = 3) -> list[PaperRecord]:
        records: list[PaperRecord] = []
        for index in range(1, top_k + 1):
            paper_url = f"https://example.com/papers/{task.id}/{index}"
            records.append(
                PaperRecord(
                    paper_id=str(uuid5(NAMESPACE_URL, paper_url)),
                    title=f"{task.title} - Mock Paper {index}",
                    authors=["PaperDesk Skeleton", f"Author {index}"],
                    year=2024 + (index % 2),
                    abstract=(
                        "This is a mock online paper result generated by the PaperDesk "
                        "00/01 runnable skeleton. It exists to validate the workflow only."
                    ),
                    url=paper_url,
                    doi=f"10.0000/paperdesk.{index}",
                    venue="PaperDesk Mock Archive",
                    source="mock_provider",
                )
            )
        return records
