"""Online paper search agent stub."""

from __future__ import annotations

from app.models import PaperRecord, TodoTask


class PaperSearchAgent:
    """Return mock online paper records for a TODO item."""

    def search(self, task: TodoTask, *, top_k: int = 3) -> list[PaperRecord]:
        records: list[PaperRecord] = []
        for index in range(1, top_k + 1):
            records.append(
                PaperRecord(
                    title=f"{task.title} - Mock Paper {index}",
                    authors=["PaperDesk Skeleton", f"Author {index}"],
                    year=2024 + (index % 2),
                    abstract=(
                        "This is a mock online paper result generated by the PaperDesk "
                        "00/01 runnable skeleton. It exists to validate the workflow only."
                    ),
                    url=f"https://example.com/papers/{task.id}/{index}",
                    doi=f"10.0000/paperdesk.{index}",
                )
            )
        return records

